# Generated by Django 6.0.5 on 2026-05-26 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoRastreamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('criado', 'Pedido criado'), ('aprovado', 'Aprovado'), ('em_separacao', 'Em separação'), ('em_transito', 'Em trânsito'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado'), ('observacao', 'Observação')], max_length=20)),
                ('descricao', models.TextField()),
                ('localizacao', models.CharField(blank=True, max_length=200)),
                ('automatico', models.BooleanField(default=False)),
                ('data_evento', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='pedidos.pedido')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Rastreamento',
                'verbose_name_plural': 'Eventos de Rastreamento',
                'ordering': ['-data_evento'],
            },
        ),
    ]
