# Generated by Django 6.0.5 on 2026-05-22 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDoacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('condicao', models.CharField(choices=[('novo', 'Novo'), ('semi_novo', 'Semi-novo'), ('usado_bom', 'Usado - Bom estado'), ('usado_regular', 'Usado - Estado regular')], max_length=20)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='disponivel', max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='doacoes/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doacoes.categoriadoacao')),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doacoes_feitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
