# Generated by Django 6.0.5 on 2026-05-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0003_check_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='doacao',
            name='chk_doacao_quantidade_positiva',
        ),
        migrations.RemoveConstraint(
            model_name='doacao',
            name='chk_doacao_status_valido',
        ),
        migrations.RemoveConstraint(
            model_name='doacao',
            name='chk_doacao_condicao_valida',
        ),
        migrations.RemoveIndex(
            model_name='doacao',
            name='idx_doacao_status_cat',
        ),
        migrations.RemoveIndex(
            model_name='doacao',
            name='idx_doacao_doador_status',
        ),
    ]
