# Generated by Django 6.0.5 on 2026-05-27 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_voluntario'),
        ('pedidos', '0003_check_constraints'),
    ]

    operations = [
    ]
