# Generated by Django 6.0.5 on 2026-05-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_merge_0002_pedido_voluntario_0003_check_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pedido',
            name='chk_pedido_quantidade_positiva',
        ),
        migrations.RemoveConstraint(
            model_name='pedido',
            name='chk_pedido_status_valido',
        ),
        migrations.RemoveConstraint(
            model_name='pedido',
            name='chk_pedido_prioridade_valida',
        ),
        migrations.RemoveIndex(
            model_name='pedido',
            name='idx_pedido_rastreio',
        ),
        migrations.RemoveIndex(
            model_name='pedido',
            name='idx_pedido_status_data',
        ),
    ]
