# Generated by Django 6.0.5 on 2026-05-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pagina_descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pagina_historia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pagina_missao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pagina_publicada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pagina_titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='placa_veiculo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='razao_social',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_veiculo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('doador', 'Doador'), ('beneficiario', 'Beneficiário'), ('voluntario', 'Voluntário'), ('ong', 'ONG')], default='doador', max_length=20),
        ),
    ]
