# Generated by Django 6.0.5 on 2026-05-26 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pedido_criado', 'Pedido criado'), ('pedido_aprovado', 'Pedido aprovado'), ('pedido_em_transito', 'Pedido em trânsito'), ('pedido_entregue', 'Pedido entregue'), ('nova_doacao', 'Nova doação disponível'), ('avaliacao_recebida', 'Avaliação recebida'), ('sistema', 'Notificação do sistema')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
