# Generated by Django 6.0.5 on 2026-05-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='avaliacao',
            name='chk_nota_geral_1_5',
        ),
        migrations.RemoveConstraint(
            model_name='avaliacao',
            name='chk_nota_atendimento_1_5',
        ),
        migrations.RemoveConstraint(
            model_name='avaliacao',
            name='chk_nota_prazo_1_5',
        ),
    ]
